Fix IDs, conversion and MT for multiple org
biomage-ltd/data-ingest pull request #17
Opened 2021-04-20 17:28 UTC by JuanluOnieva-biomage

2021-04-20 19:06 UTC, cosa65 commented on src/1_Preproc.r
> +      if(file.exists(paste("/input", sample, "features.tsv.gz", sep = "/")))
Should this work for `genes.tsv.gz` too?

2021-04-20 21:23 UTC, alexvpickering requested changes

2021-04-20 21:23 UTC, alexvpickering commented on src/1_Preproc.r
> +        annotation_features[[sample]] <- read.delim(paste("/input", sample, "features.tsv.gz", sep = "/"), header = FALSE)
```suggestion
      sample_dir <- file.path('/input', sample)
      scdata[[sample]] <- Read10X(sample_dir, gene.column = 1)  
      fpaths <- file.path(sample_dir, c('genes.tsv', 'features.tsv.gz'))
      fpath <- fpaths[file.exists(fpaths)][1]
      if (!is.na(fpath)) annotation_features[[sample]] <- read.delim(fpath, header = FALSE)
```

2021-04-20 21:23 UTC, alexvpickering commented on src/1_Preproc.r
> +    annotation_features <- unique(do.call('rbind', annotation_features))
Can you double check that the annotation `data.frame` that gets stored in `@misc` always retains the same index as the Seurat object? I'm not sure that it will with this approach

2021-04-21 06:34 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +annotations$name[idt_duplicated] <- paste(annotations$name[idt_duplicated], annotations$input[idt_duplicated], sep = "-")
I thought in grep by `"-ENS"` but by adding a space I think that it will also works.

2021-04-21 06:39 UTC, JuanluOnieva-biomage commented on src/1_Preproc.r
> +    annotation_features <- unique(do.call('rbind', annotation_features))
I think that we do not require to have the same index, since every time that we look for a gene name we use the function `match`.  I`ll remove saving the `RDS` here becauase it was for debugging

2021-04-21 07:47 UTC, seb-mueller requested changes
Nice work, but I'd like to have it amended as in the comments, happy for a call about it

2021-04-21 07:47 UTC, seb-mueller commented on src/1_Preproc.r
> +
I'm suggesting to annotate this approach (hope I got it right):
```suggestion
# overall feature annotation is derived from input data saved in genes.tsv features.tsv.gz
# since each sample only carries a subset of annotation for it's expressed genes, the annotation for all samples is merged.
# this is an excerpt of features.tsv.gz
# ENSG00000237613 | FAM138A | Gene Expression
# ENSG00000186092 | OR4F5 | Gene Expression

```

2021-04-21 07:47 UTC, seb-mueller commented on src/1_Preproc.r
> +    annotation_features <- unique(do.call('rbind', annotation_features))
I agree with Juan, i thinks thats fine. 
However I don't like the naming here, `annotation_features` is first a list and then a data.frame, this makes it hard to debug, I suggest to rename to `annotation_features_df` from this line

2021-04-21 07:47 UTC, seb-mueller commented on src/1_Preproc.r
> +    colnames(annotation_features) <- c("input", "name")
Shouldn't this be EID and gene name instead, not sure what "input" means?

2021-04-21 07:47 UTC, seb-mueller commented on src/3_Seurat.r
> +    if(any(grepl("^mt-", annotations$name, ignore.case = T))){
Nice!

2021-04-21 07:47 UTC, seb-mueller commented on src/4_Prepare_experiment.r
> +annotations$name[is.dup] <- paste(gname[is.dup], annotations$input[is.dup], sep = " - ")
So this is overwriting $name, we should keep the original gene name in a seperate column i.e. $gene_name

2021-04-21 08:08 UTC, JuanluOnieva-biomage commented on src/1_Preproc.r
> +    colnames(annotation_features) <- c("input", "name")
Yes, however in the worker as well as the in the pipeline we use the annotation from gprofiler, so in order to do not break anything I kept the same colnames that we had in gene_annotation misc slot

2021-04-21 08:11 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +annotations$name[is.dup] <- paste(gname[is.dup], annotations$input[is.dup], sep = " - ")
But `annotations` is specific for each experiment, and since we have a unique ENSEMBL id, with which purpose we would like to keep also the original gene_name. Because in the case that we need we can gsub the ensembl id. However, if you think that we should I am happy to change it :)

2021-04-21 12:55 UTC, alexvpickering commented on src/1_Preproc.r
> +    annotation_features <- unique(do.call('rbind', annotation_features))
Haha I personally prefer to overwrite since it's not being used again. I feel like with R you often need to do quite a bit of gymnastics to get what you want and having different names for every intermediate object is overkill. 

I definitely prefer (and it is standard and enforced with most classes) to have row/col metadata have the same index. Indexing is also much faster for the minor upfront effort.

2021-04-21 13:00 UTC, alexvpickering commented on src/4_Prepare_experiment.r
> +annotations$name[is.dup] <- paste(gname[is.dup], annotations$input[is.dup], sep = " - ")
I agree with Seb it's not a bad idea to keep the original. It makes it more likely that someone without our familiarity will discover the discrepancy.

2021-04-21 13:08 UTC, alexvpickering approved these changes

2021-04-21 13:41 UTC, JuanluOnieva-biomage commented on src/1_Preproc.r
> +    annotation_features <- unique(do.call('rbind', annotation_features))
All right, I have index the annotation by rownames in the seurat object

2021-04-21 13:42 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +annotations$name[is.dup] <- paste(gname[is.dup], annotations$input[is.dup], sep = " - ")
I have create a colnames `original_name`. And regarding the separator if fined to me to leave the space :) (gene - ENSEMBL)

2021-04-21 13:57 UTC, alexvpickering commented on src/4_Prepare_experiment.r
> +annotations <- annotations[match(rownames(seurat_obj), annotations$input), ]
Nice! Thank you for obliging me :)

2021-04-21 14:04 UTC, JuanluOnieva-biomage commented on src/1_Preproc.r
> +    colnames(annotation_features) <- c("input", "name")
Since it is something internally I don't mind. It is true that if we would like to rename we can do right now since we have only a few dataset. In that case, we need to create some tickets for the worker and pipeline. @alexvpickering @seb-mueller

2021-04-21 15:20 UTC, seb-mueller commented on src/1_Preproc.r
> +    colnames(annotation_features) <- c("input", "name")
It's really subjective and I'm not really invested, Juan, I'd let you decide. If you rename it, could you please write the ticket or let me know to write it. Thanks :)

2021-04-21 15:22 UTC, seb-mueller approved these changes
Nice work Juan, just left that one optional comment that you might or might not change the naming, up to you.

2021-04-21 15:53 UTC, merged