Check seurat object
biomage-ltd/data-ingest pull request #23
Opened 2021-04-29 20:30 UTC by ogibson-biomage

![image](https://user-images.githubusercontent.com/76957896/116614667-99cf4280-a910-11eb-99cd-f41cd3ebc7f1.png)

Had to include the caption here to sustain my cute animal choice.

2021-04-29 20:32 UTC, ivababukova commented
It's good that you kept the caption, I was just about to object the cuteness :D

2021-04-30 08:40 UTC, seb-mueller commented
This is a nice starting point for testing r-objects. In it's current format, it focuses to test bits we have added to the seurat object, i.e. `meta.data` and `misc`, but not general integrity of a seurat object. This is fine for now since we mostly care about our bits. Going forward, we might however add use this for checks also in pipeline after each filter.

I've tested for this experiment:
`biomage experiment pull production 87583e3eb71e4ad3f9ff60f10305e048`
and all tested were pasted on the resulting object.

But when pulling this one:
`biomage experiment pull production e52b39624588791a7889e39c617f669e` 
and validating the object I get this:
```── Failure (test.r:46:9): Validating misc ──────────────────────────────────────
"color_pool" %in% names(misc) is not TRUE

`actual`:   FALSE
`expected`: TRUE

── Failure (test.r:47:9): Validating misc ──────────────────────────────────────
misc$color_pool inherits from `'NULL'` not `'character'`.

── Warning (test.r:48:9): Validating misc ──────────────────────────────────────
longer object length is not a multiple of shorter object length
Backtrace:
 1. testthat::expect_true(all(misc$gene_annotations$input == rownames(scdata)))
 2. testthat::quasi_label(enquo(object), label, arg = "object")
 3. rlang::eval_bare(expr, quo_get_env(quo))

── Failure (test.r:48:9): Validating misc ──────────────────────────────────────
all(misc$gene_annotations$input == rownames(scdata)) is not TRUE

`actual`:   FALSE
`expected`: TRUE

── Failure (test.r:49:9): Validating misc ──────────────────────────────────────
sum(duplicated(misc$gene_annotations$name)) == 0 is not TRUE

`actual`:   FALSE
`expected`: TRUE
```
I think the color_pool has not been added, could you have a look if you get the same? It might be a problem with this experiment rather than the test, so this can than still be merged, just wanted you to have a look at it.

2021-04-30 08:42 UTC, seb-mueller commented
Accidentally closed it, reopened it...

2021-05-03 13:24 UTC, ogibson-biomage commented
> This is a nice starting point for testing r-objects. In it's current format, it focuses to test bits we have added to the seurat object, i.e. `meta.data` and `misc`, but not general integrity of a seurat object. This is fine for now since we mostly care about our bits. Going forward, we might however add use this for checks also in pipeline after each filter.
> 
> I've tested for this experiment:
> `biomage experiment pull production 87583e3eb71e4ad3f9ff60f10305e048`
> and all tested were pasted on the resulting object.
> 
> But when pulling this one:
> `biomage experiment pull production e52b39624588791a7889e39c617f669e`
> and validating the object I get this:
> 
> ```
> "color_pool" %in% names(misc) is not TRUE
> 
> `actual`:   FALSE
> `expected`: TRUE
> 
> ── Failure (test.r:47:9): Validating misc ──────────────────────────────────────
> misc$color_pool inherits from `'NULL'` not `'character'`.
> 
> ── Warning (test.r:48:9): Validating misc ──────────────────────────────────────
> longer object length is not a multiple of shorter object length
> Backtrace:
>  1. testthat::expect_true(all(misc$gene_annotations$input == rownames(scdata)))
>  2. testthat::quasi_label(enquo(object), label, arg = "object")
>  3. rlang::eval_bare(expr, quo_get_env(quo))
> 
> ── Failure (test.r:48:9): Validating misc ──────────────────────────────────────
> all(misc$gene_annotations$input == rownames(scdata)) is not TRUE
> 
> `actual`:   FALSE
> `expected`: TRUE
> 
> ── Failure (test.r:49:9): Validating misc ──────────────────────────────────────
> sum(duplicated(misc$gene_annotations$name)) == 0 is not TRUE
> 
> `actual`:   FALSE
> `expected`: TRUE
> ```
> 
> I think the color_pool has not been added, could you have a look if you get the same? It might be a problem with this experiment rather than the test, so this can than still be merged, just wanted you to have a look at it.

Sure Seb! I'll check!

2021-05-03 14:19 UTC, JuanluOnieva-biomage requested changes

2021-05-03 14:19 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +config.configureEmbedding <- list(auto="false",
Is there any specific reason of setting into `false`?

2021-05-03 14:19 UTC, JuanluOnieva-biomage commented on src/test_object.r
> +        expect_true(nrow(scdata) > 100, "Seurat") # more than 100 barcodes
I think 100 barcodes may be too restrictive for some experiments (in particular for those that are already pre-filtered)

2021-05-03 14:19 UTC, JuanluOnieva-biomage commented on src/test_object.r
> +        expect_true("percent.mt" %in% colnames(md))
In organism like ggallus we are not going to have the `percent.mt`. We are going to have `percent.mt` in those experiments that have at least one "MT-" gene in any of the sample [see code](https://github.com/biomage-ltd/data-ingest/blob/e15cfbe53a51f7b62c40d56977d7d20987e4fe56/src/3_Seurat.r#L69) (we grep over annotation, which was constructed based on the union of all `features.tsv` files).

2021-05-03 15:28 UTC, ogibson-biomage commented on src/4_Prepare_experiment.r
> +config.configureEmbedding <- list(auto="false",
Yes, this is because of [this](https://this-is-biomage.slack.com/archives/C01CP46TJ0Z/p1620033788038700) issue

2021-05-03 15:28 UTC, ogibson-biomage commented on src/test_object.r
> +        expect_true(nrow(scdata) > 100, "Seurat") # more than 100 barcodes
Tuning it down

2021-05-04 22:08 UTC, alexvpickering commented on src/test_object.r
> +        expect_true(nrow(scdata) > 100, "Seurat") # more than 100 barcodes
isn't `scdata` genes x cells? so This is checking that there are at least 100 genes?

2021-05-04 22:16 UTC, alexvpickering commented on src/test_object.r
> +        expect_true("percent.mt" %in% colnames(md))
It looks to be setting it to zero if it doesn't exist:

![image](https://user-images.githubusercontent.com/15719520/117076702-ae825080-aceb-11eb-9482-2e2f1ab96004.png)

Maybe that behaviour should be changed though?

2021-05-04 22:20 UTC, alexvpickering commented on src/test_object.r
> +        expect_true("percent.mt" %in% colnames(md))
Why are we setting `percent.mt` to zero when we don't find it in a given sample (but it is in the union of samples) but leaving it unset if it's not in the union of samples?

![image](https://user-images.githubusercontent.com/15719520/117077026-3d8f6880-acec-11eb-8bce-6311937297fd.png)

2021-05-05 06:52 UTC, JuanluOnieva-biomage commented on src/test_object.r
> +        expect_true(nrow(scdata) > 100, "Seurat") # more than 100 barcodes
Yes, you are right, the line that should be removed is the line 9, which refers to ncol

2021-05-05 06:59 UTC, JuanluOnieva-biomage commented on src/test_object.r
> +        expect_true("percent.mt" %in% colnames(md))
I do not remember well, maybe @seb-mueller can help us. We had a meeting with Marcell some weeks ago and we decided a quick fix for that. I think that we disable the mitochondrial filter in the case that there is no information of MT but I'm not sure. It could be a good point to add `percent.mt` to 0, nevertheless we need to advice the user that we cannot identify mitochondrial content with our current method.

2021-05-06 21:26 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +config.configureEmbedding <- list(auto="false",
Thanks! I'll resolve, maybe we need to reorganize the config schema and discuss if we need in the future the `auto` parameter.

2021-05-06 21:27 UTC, JuanluOnieva-biomage approved these changes

2021-05-06 23:57 UTC, merged