Fix CR v2 gz format
biomage-ltd/data-ingest pull request #25
Opened 2021-05-03 17:55 UTC by JuanluOnieva-biomage

*Link to issue:*

https://biomage.atlassian.net/browse/BIOMAGE-852?atlOrigin=eyJpIjoiNjdhYmE0NzRjODJjNDY4NWFkYTRiNTk5NDVhMDQ5NTEiLCJwIjoiaiJ9

*Anything else the reviewers should know about the changes here*

`Read10X()` from Seurat only read CR V2 for gz version, but data-upload will gz all files so this function will fail with CR V2. To handle it, we will take advantage of `read.table` in R, which does not distinguish between compressed file or not compressed. By renaming the file just before and after `Read10X()` we cheat the function and we achieve having all files in gz format.

2021-05-03 17:57 UTC, JuanluOnieva-biomage commented on src/1_Preproc.r
> +prepare_scrublet_table <- function(scdata, sample_name, min.features = 10) {
I have changed this value to be coherent with the commit [PR #22](https://github.com/biomage-ltd/data-ingest/commit/e15cfbe53a51f7b62c40d56977d7d20987e4fe56)

2021-05-04 21:38 UTC, alexvpickering requested changes

2021-05-04 21:38 UTC, alexvpickering commented on src/1_Preproc.r
> +}
```suggestion
```

Just clarifying that these can be file paths so `removegz` would have made e.g. `s='brain_dgz/genes.tsv.gz'` into `'brain_/genes.tsv'`. Also, `paste0`, `gsub`, and `file.rename` are vectorized so no need to loop. Makes for a lot less code and we can be a little more explicit about whats happening (instead of `rename_files_to_fit_Cellranger_v2`). Infact since they only get called once each inlining it makes it even cleaner (see below suggestions).

2021-05-04 21:38 UTC, alexvpickering commented on src/1_Preproc.r
> +      }
```suggestion
      # Now, we can add again the gz suffix
      if (is_v2) file.rename(sample_fpaths, paste0(fpaths, '.gz'))
```

2021-05-05 07:20 UTC, JuanluOnieva-biomage commented on src/1_Preproc.r
> +      }
Here `fpaths` no longer existis so I'll change in the next commit.

2021-05-05 11:57 UTC, alexvpickering commented on src/1_Preproc.r
> +      }
Ah yes, good catch. Coding on github not the easiest to spot sillyness :-)

2021-05-05 11:59 UTC, alexvpickering commented
Looks good to me - great work @JuanluOnieva! Not sure to what extent it has been tested but it should go through the wringer today as I'll be re-ingesting a bunch of data.

2021-05-05 11:59 UTC, alexvpickering approved these changes

2021-05-05 12:23 UTC, seb-mueller approved these changes
lgtm

2021-05-05 12:23 UTC, seb-mueller commented on src/1_Preproc.r
> +  cell_ranger_v2 <- c("genes.tsv.gz", "barcodes.tsv.gz", "matrix.mtx.gz")
```suggestion
  # Cell ranger v2 does in fact produce non gunzipped outputs, but since during
  # data-upload gzip compresses all non-compressed file, so we expect files with *.gz ending here
  cell_ranger_v2 <- c("genes.tsv.gz", "barcodes.tsv.gz", "matrix.mtx.gz")
```
Just a suggestions to point out this hacky workaround

2021-05-06 21:13 UTC, merged