Move into scDblFinder
biomage-ltd/data-ingest pull request #26
Opened 2021-05-04 18:47 UTC by JuanluOnieva-biomage

**Link to issue:**

https://biomage.atlassian.net/browse/BIOMAGE-895?atlOrigin=eyJpIjoiYTYzMjAxNmQ1ZTBkNDNlMThjNWU3YTM3ZTZlZTY2YjYiLCJwIjoiaiJ9

**Anything else the reviewers should know about the changes here**

We are going to use `scDblFinder` for obtaining doublets scores. As input it uses the count matrix without empyDrops (a smooth filter with `min.features`=10 has been used).

2021-05-04 20:14 UTC, alexvpickering requested changes

2021-05-04 20:14 UTC, alexvpickering commented on src/2-2_Compute-metrics_doublets.r
> +    df_doublet_scores <- data.frame(Barcodes=rownames(scdata_DS@colData), doublet_scores=scdata_DS@colData$scDblFinder.score)
```suggestion
    df_doublet_scores <- data.frame(Barcodes=rownames(scdata_DS@colData), doublet_scores=scdata_DS@colData$scDblFinder.score,
    doublet_class = scdata_DS@colData$scDblFinder.class)
```

We should store what `scDblFinder` classifies as a doublet as it is part of the algorithm (not just the score) and should be used to set the default threshold. [Here](https://bioconductor.org/packages/release/bioc/vignettes/scDblFinder/inst/doc/2_scDblFinder.html#thresholding-and-local-calibration) is the relevant part of the vignette that describes thresholding on the doublet score. If you agree, please make sure it is also being stored in the final Seurat object as well.

2021-05-04 20:14 UTC, alexvpickering commented on src/2-2_Compute-metrics_doublets.r
> +compute_doublet_scores <- function(scdata, sample_name, min.features = 10) {
`scDblFinder` should be run after empty droplets have been removed. [See usage](https://bioconductor.org/packages/release/bioc/vignettes/scDblFinder/inst/doc/2_scDblFinder.html#usage) in vignette

2021-05-04 20:14 UTC, alexvpickering commented on src/2-2_Compute-metrics_doublets.r
> +}
Another option is to create a single matrix and use the `samples` argument to `scDblFinder`. It splits the data like you do here but [trains the classifier globally](https://bioconductor.org/packages/release/bioc/vignettes/scDblFinder/inst/doc/2_scDblFinder.html#splitting-captures). Might give slightly better predictions.

2021-05-05 06:21 UTC, JuanluOnieva-biomage commented on src/2-2_Compute-metrics_doublets.r
> +    df_doublet_scores <- data.frame(Barcodes=rownames(scdata_DS@colData), doublet_scores=scdata_DS@colData$scDblFinder.score)
I agree. I'll change the code to add it also in the seurat object

2021-05-05 06:24 UTC, JuanluOnieva-biomage commented on src/2-2_Compute-metrics_doublets.r
> +compute_doublet_scores <- function(scdata, sample_name, min.features = 10) {
I thing that we can use the `min.features` to try to avoid obvious emptydrops in `scDblFinder`, so my guess is to run it with this `min.features` parameter set to the same number that later we will use to construct the seurat object

2021-05-05 06:27 UTC, JuanluOnieva-biomage commented on src/2-2_Compute-metrics_doublets.r
> +}
Good point, I thought about that, but this script is going to migrate to run over an unique sample in a pipeline step, so if you think that it is relevant to compute droplets with the whole experiment we could move this as a step in data-processing, but the disadvantage of this is that we could lead to run `scDblFinder` multiple times (each time the user run the data-processing)

2021-05-05 07:49 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +    filterSettings = list(probabilityThreshold = 0.5, binStep = 0.05)
This value should not be reached, since we will add a specific value per sample, however, I see that scDblfinder gives greater score than scrublet, so I think that we should increased to 0.5. Does sound good @alexvpickering?

2021-05-05 09:45 UTC, seb-mueller reviewed
lgtm appart from a few comments.
Also, a central issues with doublet finding is gettting the [expected proportions](https://bioconductor.org/packages/release/bioc/vignettes/scDblFinder/inst/doc/2_scDblFinder.html#expected-proportion-of-doublets) in a sensible range. This is to some degree controlled by the `dbr` which I've explicitly added. By default this is assumed to be 1% per thousandcells captured, which should be good for now.
However, is it possible to calculate the actual doublet rate for a given sample which we would need to output in the stats-table later? My thought is to have that information available at the filter stage. Maybe it is as easy as calculating #single/#doublet from the meta.data, in which case this should suffice.

2021-05-05 09:45 UTC, seb-mueller commented on src/2-2_Compute-metrics_doublets.r
> +}
I tend to agree with Juan, splitting it up this way feeds much better in our efforts to handle samples separately. Indeed, it is a trade-off with potentially slightly better performance, but I think it doesn't outweight the fact that we can feed it a lot better in a per sample workflow this way.

2021-05-05 09:45 UTC, seb-mueller commented on src/3_Seurat.r
> +    seurat_obj@meta.data[idt, "doublet_class"] <- scores[idt, "doublet_class"]
What happens for cells without scores/class calculated? Do they get `NA` assigned this way? Just thinking of edge cases where those get passed on to the pipeline filter (i.e. by deactivating all filters before doublet-filtering). How would they get handled? Maybe it's better to give them an explicte score (i.e. being a singlet).

2021-05-05 09:45 UTC, seb-mueller commented on src/help.r
> +    colnames(scores) <- c("barcodes", "doublet_scores", "doublet_class")
Are the "new" doublet_scores in the same range as for scrublet? If no, we need to create a ticket to adjust the UI I suppose

2021-05-05 09:45 UTC, seb-mueller commented on src/2-2_Compute-metrics_doublets.r
> +    scdata_DS <- scDblFinder(scdata[, Matrix::colSums(scdata>0)>=min.features])
```suggestion
    scdata_DS <- scDblFinder(scdata[, Matrix::colSums(scdata>0)>=min.features], dbr = NULL, trajectoryMode = FALSE)
```
I feel we should make some important parameters explicit since we might want to be able to change them in the future. Feel free to ignore when you disagree :)

2021-05-05 11:20 UTC, JuanluOnieva-biomage commented on src/3_Seurat.r
> +    seurat_obj@meta.data[idt, "doublet_class"] <- scores[idt, "doublet_class"]
I run some test, and it seems that it always assigns a value. So we are not going to have NA in `doublet_scores` neither `doublet_class`.

2021-05-05 11:20 UTC, JuanluOnieva-biomage commented on src/help.r
> +    colnames(scores) <- c("barcodes", "doublet_scores", "doublet_class")
Yes, they are from 0 to 1

2021-05-05 11:21 UTC, JuanluOnieva-biomage commented on src/2-2_Compute-metrics_doublets.r
> +    scdata_DS <- scDblFinder(scdata[, Matrix::colSums(scdata>0)>=min.features])
Happy with it!

2021-05-05 11:38 UTC, alexvpickering commented on src/2-2_Compute-metrics_doublets.r
> +compute_doublet_scores <- function(scdata, sample_name, min.features = 10) {
I would go with `emptyDrops` score with recommended cutoff (`e.out$FDR <= 0.001`) for this calculation. `min.features=10` is not nearly enough to exclude obviously empty droplets. See e.g. this typical barcode-ranks plot:

![image](https://user-images.githubusercontent.com/15719520/117134884-0b691f80-ad5b-11eb-8430-6040d6c56852.png)

UMI = 10 is still way down in the nether regions. If you want to use it like this I would test it both ways and possibly contact the authors of `scDblFinder` and ask them about any unintended consequences of including a large number of empty droplets. One that I anticipate is that empty droplets will form there own cluster and doublet simulation with cells from the empty droplets cluster will result in more doublet calls than is warrented (empty drop + real cell ~= real cell).

2021-05-05 11:42 UTC, alexvpickering commented on src/2-2_Compute-metrics_doublets.r
> +}
I'm convinced. Since we are migrating to the pipeline which we want to run per sample let's keep it seperate

2021-05-05 11:48 UTC, alexvpickering commented on src/4_Prepare_experiment.r
> +    filterSettings = list(probabilityThreshold = 0.5, binStep = 0.05)
I think the default should be based on the called doublets from `scDblFinder` as per other comment on the score not being the final output of the algorithm. So something like this:

`probabilityThreshold <- min(scdata$doublet_score[scdata$doublet_class == 'doublet'])`

2021-05-05 11:56 UTC, seb-mueller commented on src/2-2_Compute-metrics_doublets.r
> +compute_doublet_scores <- function(scdata, sample_name, min.features = 10) {
Hmm, indeed, this could be an issue indeed. And yes, including many ambient cells as with this threshold might also lead to an heavily bias  calculation the  proportion of doublets (e.g. if all ambient cells are either assigned single or doublet, it will bost the respective proportion considerably). So I agree with @alexvpickering to use `e.out$FDR <= 0.001` . However if we get already filtered cells as input, the FDR is not available, in which case all cells should be used. So there would be a check needed (filtered/unfiltered)

2021-05-05 11:59 UTC, seb-mueller commented on src/3_Seurat.r
> +    seurat_obj@meta.data[idt, "doublet_class"] <- scores[idt, "doublet_class"]
Good to know, what values is it assigning? Singlet or doublet? This might be important for the filtering in pipeline (could you add a comment on your findings?) Thanks!

2021-05-05 13:55 UTC, alexvpickering commented on src/2-2_Compute-metrics_doublets.r
> +compute_doublet_scores <- function(scdata, sample_name, min.features = 10) {
Yes if there is no emptyDrops output then keep everything (filtered cell ranger output uses emptyDrops so it should be the same).

2021-05-06 11:27 UTC, alexvpickering approved these changes
Looks good to me. Thanks for the ninja coding as usual @JuanluOnieva!

2021-05-06 21:07 UTC, JuanluOnieva-biomage commented on src/2-2_Compute-metrics_doublets.r
> +compute_doublet_scores <- function(scdata, sample_name, min.features = 10) {
To sum up, we will keep as it is (using `min.features`). Another point that may support it, is the use case when the user select a value smaller han 0.001 for emptyDrops in data processing. In that case, we will have NA values in doublet scores. So, for now, we are going to use the same `min.features` as the one that is used to create the seurat object, with the purpose to have all cells present in the seurat object with a doublet scores.

2021-05-06 21:08 UTC, JuanluOnieva-biomage commented on src/4_Prepare_experiment.r
> +    filterSettings = list(probabilityThreshold = 0.5, binStep = 0.05)
Yes, you are right. Later on, I used this logic for each sample separately (line 326)

2021-05-06 21:11 UTC, JuanluOnieva-biomage commented on src/3_Seurat.r
> +    seurat_obj@meta.data[idt, "doublet_class"] <- scores[idt, "doublet_class"]
I have researched on it, and there is no information about possible `NA`values after performing `scDblFinder`. As Alex said, they have their own algorithm to classify in singlet or doublet based on the doublet_scores, but there is no case in which these values may be missing.

2021-05-06 21:19 UTC, merged