New workflow logic
biomage-ltd/data-ingest pull request #9
Opened 2021-03-30 19:14 UTC by JuanluOnieva-biomage

Link to issue

https://biomage.atlassian.net/browse/BIOMAGE-693?atlOrigin=eyJpIjoiODdkODEyNjllNzc3NDJkOTk5YmVhZWFiOTJiYTRmNmUiLCJwIjoiaiJ9

Anything else the reviewers should know about the changes here

Tasks related to this PR:
 - Adding the capability to ingest two version of cell ranger (V2 {genes.tsv, matrix.mtx, barcodes.tsv} and V3 {features.tsv.gz, barcodes.tsv.gz and matrix.mtx.gz}) 
 - Running emptyDrops and scrublet independently for each sample.
 - Getting a rds seurat object per sample
 - Adding a flag filtered in samples-table and disable the classifier when the data is pre-filtered
 - Adding an unique uuid per sample in samples-table

Anything else the reviewers should know about to run the data-ingest:

- To organize the input folder, inside it we need to create a folder per sample, and inside this folder the cellranger files should be in the above format (V2 or V3)
- meta.json file is required in the input folder. The schema is the following:

`
{
    "name": "Multisample-murine-gamma-delta-T-wt-beta2-KO-lungs",
    "organism": "mmusculus",
    "samples": ["KO", "WT1", "WT2"],
    "input": {
        "type": "10x"
    }
}
`

Example of samples-table json --> [link](https://docs.google.com/document/d/1NMvobpuDFrRYv2CAPf7ryxfkHzpAVX9n0IjLrMiuvTs/edit?usp=sharing)

2021-03-30 21:48 UTC, alexvpickering commented on src/5_Upload-to-aws.py
> +"""
Still working on or needs uncommenting so that it uploads?

2021-03-31 06:29 UTC, JuanluOnieva-biomage commented on src/5_Upload-to-aws.py
> +"""
Needs uncomementing. For testing purpose I have commented just to not upload an experiment each time that I test, but I`ll fix it

2021-03-31 09:27 UTC, seb-mueller requested changes
Very nice work Juanlu!
I've added quite a few comments which we will go over in a call.

In general:
It seems that at them moment most step is are run for all samples collectively. 
Going forward, we should change this to be able to process samples independenlty (until they need to be merged) so we can parallize the workflow and a "broken" sample will not impact the other samples as much.

2021-03-31 09:27 UTC, seb-mueller commented on src/3_Seurat.r
> +if (length(config$samples)>0){
How do samples get "selected"?

2021-03-31 09:27 UTC, seb-mueller commented on src/3_Seurat.r
> +    seurat_obj <- Seurat::CreateSeuratObject(scdata, assay='RNA', min.cells=1, min.features=1, meta.data=metadata, project = config$name)
min.cells should be matched with min.cells above in the code (where it is 3). Ideally, use a parameter for this function.

2021-03-31 10:12 UTC, seb-mueller commented on src/3_Seurat.r
> +    }
Seb: to ask Marcel about engeneering out Mito in UI/API

2021-03-31 10:18 UTC, seb-mueller commented on src/4_Prepare_experiment.r
> +    seurat_obj <- seurat_obj_list[[1]]
Alwasy have sample name as part of barcode-name because of:
https://github.com/biomage-ltd/pipeline/blob/26d02e3dbfaed408ea9c1772108e8a644ad0795b/remoter-server/src/classifier.r#L94

2021-03-31 18:57 UTC, merged